Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [87]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

data = load_iris()



#1. Extract feature matrix as NumPy array
feature_matrix= data.data
# print(feature_matrix)]

feature_names= data.feature_names
print(feature_names)

#2. Compute: Mean Median Standard deviation Variance (for each feature)

mean = np.mean(feature_matrix, axis=0)  #axix=0 means column wise
median =np.median(feature_matrix, axis=0)
std=np.std(feature_matrix, axis=0)
variance=np.var(feature_matrix, axis=0)
print("mean :",mean)
print("meadian :",median)
print("std :",std)
print("variance :",variance)

#3.Identify: Which feature has highest variability and why it matters in ML

max_var_index = np.argmax(variance)
print("Feaute with higest variance is :" , feature_names[max_var_index])


#4. Convert any one feature into shape (n,1) 

x= data.data
print(x.shape)

thirdFeature=x[:,2]
print(thirdFeature.shape)

fullArrayThirdFeature= thirdFeature.reshape(-1,1)
print(fullArrayThirdFeature.shape)
print(fullArrayThirdFeature)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
mean : [5.84333333 3.05733333 3.758      1.19933333]
meadian : [5.8  3.   4.35 1.3 ]
std : [0.82530129 0.43441097 1.75940407 0.75969263]
variance : [0.68112222 0.18871289 3.09550267 0.57713289]
Feaute with higest variance is : petal length (cm)
(150, 4)
(150,)
(150, 1)
[[1.4]
 [1.4]
 [1.3]
 [1.5]
 [1.4]
 [1.7]
 [1.4]
 [1.5]
 [1.4]
 [1.5]
 [1.5]
 [1.6]
 [1.4]
 [1.1]
 [1.2]
 [1.5]
 [1.3]
 [1.4]
 [1.7]
 [1.5]
 [1.7]
 [1.5]
 [1. ]
 [1.7]
 [1.9]
 [1.6]
 [1.6]
 [1.5]
 [1.4]
 [1.6]
 [1.6]
 [1.5]
 [1.5]
 [1.4]
 [1.5]
 [1.2]
 [1.3]
 [1.4]
 [1.3]
 [1.5]
 [1.3]
 [1.3]
 [1.3]
 [1.6]
 [1.9]
 [1.4]
 [1.6]
 [1.4]
 [1.5]
 [1.4]
 [4.7]
 [4.5]
 [4.9]
 [4. ]
 [4.6]
 [4.5]
 [4.7]
 [3.3]
 [4.6]
 [3.9]
 [3.5]
 [4.2]
 [4. ]
 [4.7]
 [3.6]
 [4.4]
 [4.5]
 [4.1]
 [4.5]
 [3.9]
 [4.8]
 [4. ]
 [4.9]
 [4.7]
 [4.3]
 [4.4]
 [4.8]
 [5. ]
 [4.5]
 [3.5]
 [3.8]
 [3.7]
 [3.9]
 [5.1]
 [4.5]
 [4.5]
 [4.7]
 [4.4]
 [4.1]
 [4. ]
 [4.4]
 [4.6]
 [4

#3 High variance in data means more information available for ML model to use
#4 (n,1) arraty means one feature at a time and it is ocnsidered 2D array. 2D arrays are more useful for ML model as it is clear one feature at a time.

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [317]:
from sklearn.datasets import load_iris
import numpy as np

data = load_iris()
df=pd.DataFrame(ds)

ds=data.data
features=data.feature_names
# print(features)


#Extract: First 100 samples Only last 2 features
# ds1=ds[0:100,2:4]
# ds1=ds[0:100,-2:]
last_two = df.iloc[:100, -2:]

print(ds1)
print("##########")
print(last_two)

#Use boolean masking:
mean=np.mean(ds1, axis=0)  # columnwise
print(mean) #2.861 0.786]
df=pd.DataFrame(ds1)
df=df.loc[df[0]>np.mean(df[0])]
print(df)

#Count selected samples
count=len(np.array(df[0]))
print(count)




[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

left hand side of the formula is transformed value
x - original vlaue
subtract mean of the column from each value
after subtract, mean of the column becomes zero
divide by std

ML models work better when:

1. features are on same scale

2. no feature dominates due to large values

In [140]:

arr= np.array(df)


mean = np.mean(arr, axis=0)
std= np.std(arr, axis=0)
scaledArr=(arr-mean)/std
# print(scaledArr)

mean= np.mean(scaledArr,axis=0)
std=np.std(scaledArr, axis=0)
print(mean)
print(std)

[4.71844785e-16 8.30446822e-16]
[1. 1.]


Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [ ]:
#3 identifying feature types is important before modeling because
1. Model treats numberical and categorical dtaa differently.
2. some model work with numerical data only like linear regression etc
3. pre-processing could be different for numerical vs categorical
4. scaling is required for numberical
5. Encoding may be required for categorical for better interprestation by model                  

                                     
    

In [155]:
import seaborn as sns

ds = sns.load_dataset("titanic")
# print(ds)

#Display: head(), tail() info(), describe()
ds.head()
ds.tail()
ds.describe()

#Identify: Missing 
missing =ds.isnull().sum()
print(missing)

#identify Numerical vs categorical features

numerical_col = ds.select_dtypes(include=['int64', 'float64']).columns
print("Numerical:",list(numerical_col))

category_col = ds.select_dtypes(include=['object']).columns
print("Category:",list(category_col))

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64
Numerical: ['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare']
Category: ['sex', 'embarked', 'who', 'embark_town', 'alive']


Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [190]:
ds = sns.load_dataset("titanic")
totalSurvived=ds.loc[ds['survived']==1].shape[0]

#Filter: Female passengers in 1st class
fc= ds.loc[(ds['sex'] == "female") & ds['pclass'] == 1]


#Compute: Survival rate for this group
survived= fc.loc[fc['survived']==1].shape[0]  # ds.shape give both (rows,columns), shape[0] gives rows only
print("women in first class survival rate is :",survived/totalSurvived)

#Compare with overall survival rate
total = ds.shape[0]
print("total survial rate :" , totalSurvived/total)

#4 Insight : Female passengers in 1st class had a much higher survival rate compared to the overall population.


women in first class survival rate is : 0.4766081871345029
total survial rate : 0.3838383838383838


Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [201]:
ds = sns.load_dataset("titanic")
df1= ds.copy()
# df1.info()

#Fill missing age using median
df1["age"].fillna(df1["age"].median(), inplace=True)
naAge= df1["age"].isnull().sum() 
print(naAge)

#Fill missing embarked using mode, mode is the value 
#that appears most in the series, so return first value hence [0]
df1["embarked"].fillna(df1["embarked"].mode()[0], inplace=True)
naEmbarked= df1["embarked"].isnull().sum() 
print(naEmbarked)

#Drop deck column
df1 = df1.drop(columns=['deck'])  
# print(df1)

#4 differnt strategies for different columns based on datatype.
# 'age' is numerical so median instead of na makes sense.
#'embarked' is a category so most populat category to fill na makes sense.
'

0
0
     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female  28.0      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male  embark_town alive  alon

/var/folders/_d/wnx6skx965v3ctrg5fcbqf_c0000gn/T/ipykernel_30760/1090094697.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["age"].fillna(df1["age"].median(), inplace=True)
/var/folders/_d/wnx6skx965v3ctrg5fcbqf_c0000gn/T/ipykernel_30760/1090094697.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values

In Pandas, axis tells the direction of operation.

📊 Meaning of axes
Axis	Meaning	Direction
axis=0	rows	top → bottom
axis=1	columns	left → right

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [226]:
ds = sns.load_dataset("titanic")

def is_alone(x):
    if x == True:
        return 1
    else:
        return 0

#Create: family_size = sibsp + parch + 1
ds['family_size']=ds['sibsp']+ds['parch']+1

#Create: is_alone (binary feature)
# ds['is_alone'] = ds['alone'].map({True: 1, False: 0})
# ds['is_alone'] = ds['alone'].map(is_alone)
# ds['is_alone'] = ds['alone'].map(lambda x: 1 if x else 0)
ds['is_alone'] = ds['alone'].apply(is_alone)

#3. survival rate by is_alone
totalSurvived=ds.loc[ds['survived']==1].shape[0]
aloneSurvived= ds.loc[(ds['is_alone'] == 1) & (ds['survived'] == 1)].shape[0]
print("rate of survival for alone travellers :",aloneSurvived/totalSurvived)

#4. Engineered feature creates new meaning and hence 
#boost perfromance. Derives hidden meaning from raw data.

342
163
rate of survival for alone travellers : 0.4766081871345029


Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [247]:
df = sns.load_dataset("tips")

print(df.head())

#1. Compute: Average tip by day
meanTip =df.groupby('day')['tip'].mean()
print(meanTip)

# Total bill by gender
billByGender =df.groupby('sex')['total_bill'].sum()
print(billByGender)

#2. Create new feature: tip_percentage
df['tip_percentage']=df['tip']/df['total_bill']*100
# print(df['tip_percentage'])

#3. Identify: Which day has highest tipping behavior
highest_day = meanTip.idxmax() #👉 idxmax() returns the index (label) of the maximum value in a Series or DataFrame column.
highest_value = meanTip.max()

print("Highest tipping day:", highest_day)
print("Average tip:", highest_value)

#4 segmentation model
# These help in grouping data into meaningful cluster or categories.


   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64
sex
Male      3256.82
Female    1570.95
Name: total_bill, dtype: float64
Highest tipping day: Sun
Average tip: 3.2551315789473683


/var/folders/_d/wnx6skx965v3ctrg5fcbqf_c0000gn/T/ipykernel_30760/1040319904.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  meanTip =df.groupby('day')['tip'].mean()
/var/folders/_d/wnx6skx965v3ctrg5fcbqf_c0000gn/T/ipykernel_30760/1040319904.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  billByGender =df.groupby('sex')['total_bill'].sum()


Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [266]:
# print(df)

avgTipRate=( df['tip']/df['total_bill']).mean()
print(avgTipRate)

#1. Filter: total_bill > 20 AND tip < 3 , return relevant columns
fittered= df.loc[(df['total_bill']>20) & (df['tip']<3), ['sex','total_bill','tip']]
print(fittered)

# Is this segment under-tipping?
underTipping= (fittered['tip']/fittered['total_bill']).mean()<avgTipRate
print("underTipping :" , underTipping)

# Anamoly detection
# a rule-based way to isolate unusual behavior, 
#identify data  point which is very different from normal behavior

0.16080258172250472
        sex  total_bill   tip
21   Female       20.29  2.75
33   Female       20.69  2.45
48     Male       28.55  2.05
57   Female       26.41  1.50
68     Male       20.23  2.01
102  Female       44.30  2.50
113    Male       23.95  2.55
119  Female       24.08  2.92
129    Male       22.82  2.18
131  Female       20.27  2.83
153    Male       24.55  2.00
166    Male       20.76  2.24
187    Male       30.46  2.00
192    Male       28.44  2.56
208    Male       24.27  2.03
210    Male       30.06  2.00
229  Female       22.12  2.88
230    Male       24.01  2.00
237    Male       32.83  1.17
240  Female       27.18  2.00
241    Male       22.67  2.00
underTipping : True


Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [276]:
import numpy as np

#Create two arrays of shape (3,2)
arr1 = np.array([
    [1, 2],
    [4, 5],
    [6, 7]
])

arr2 = np.array([
    [1, 3],
    [4, 8],
    [6, 7]
])
print(arr1.shape)

#Perform: Vertical stacking Horizontal stacking
varr= np.vstack((arr1,arr2))
print(varr)

harr= np.hstack((arr1,arr2))
print(harr)

#Reshape into (2,6)
varr= varr.reshape(2,6)
print(varr)

# Reshaping is required to have data in same structure as an ML model require.

(3, 2)
[[1 2]
 [4 5]
 [6 7]
 [1 3]
 [4 8]
 [6 7]]
[[1 2 1 3]
 [4 5 4 8]
 [6 7 6 7]]
[[1 2 4 5 6 7]
 [1 3 4 8 6 7]]


Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [291]:
import seaborn as sns

#Load dataset

ds= sns.load_dataset("titanic")
# print(ds)

#Handle missing values
# ds.info()
df= ds.copy()
# null valuesin age,deck and embarked, embarked_town
#handle null vlaues for numerical field
df['age'].fillna(ds['age'].median(), inplace=True)
#handle null vlaues for categorical data
df['deck'].fillna(ds['deck'].mode()[0], inplace=True)

print(df['age'].isna().sum()==0)
print(df['deck'].isna().sum()==0)

#Encode categorical variables (sex, embarked)
#one hot encoding for categories
#“encoding” refers to how information (usually text, categories, or symbols) is converted into a format that a computer or model can understand and process.
data= pd.get_dummies(df, columns=["sex","embarked"], drop_first=True)
# print(data)

#normalize numberical values
meanAge = df['age'].mean()
stdAge= df['age'].std()
normalizedAge = (df['age']-meanAge)/stdAge
print(normalizedAge)

# Convert to numPy array
arr= np.array(df)
print(arr)

True
True
0     -0.565419
1      0.663488
2     -0.258192
3      0.433068
4      0.433068
         ...   
886   -0.181385
887   -0.795839
888   -0.104579
889   -0.258192
890    0.202648
Name: age, Length: 891, dtype: float64
[[0 3 'male' ... 'Southampton' 'no' False]
 [1 1 'female' ... 'Cherbourg' 'yes' False]
 [1 3 'female' ... 'Southampton' 'yes' True]
 ...
 [0 3 'female' ... 'Southampton' 'no' False]
 [1 1 'male' ... 'Cherbourg' 'yes' True]
 [0 3 'male' ... 'Queenstown' 'no' True]]


/var/folders/_d/wnx6skx965v3ctrg5fcbqf_c0000gn/T/ipykernel_30760/1640378830.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(ds['age'].median(), inplace=True)
/var/folders/_d/wnx6skx965v3ctrg5fcbqf_c0000gn/T/ipykernel_30760/1640378830.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values 

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [ ]:
??????

Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [300]:
ds = sns.load_dataset("titanic")
# print(ds)

ds['age'].fillna(ds['age'].median(), inplace=True)


def age_group(age):
    if(age<18):
        return "Child"
    elif(18<=age<55):
        return "Adult"
    else:
        return "Senior"

#Create age_group: Child / Adult / Senior
ds['age_group']=ds['age'].apply(age_group)
# print(ds)

#Compute survival rate per group

survival_rate = ds.groupby("age_group")["survived"].mean()

print(survival_rate)

#4 Child has highest survival likelihood

age_group
Adult     0.364130
Child     0.539823
Senior    0.309524
Name: survived, dtype: float64


/var/folders/_d/wnx6skx965v3ctrg5fcbqf_c0000gn/T/ipykernel_30760/377767158.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds['age'].fillna(ds['age'].median(), inplace=True)


Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

errors =np.random.normal(0, 1, 1000)
errors

mean= np.mean(errors)
std = np.std(errors)


lower_bound = mean - 2 * std
upper_bound = mean + 2 * std

outliers = errors[(errors < lower_bound) | (errors > upper_bound)]

print("Outliers:", outliers)
print("Number of outliers:", len(outliers))




#High variance in model performance means your model is too sensitive to the training data—it learns patterns so 
specifically that it doesn’t generalize well to new data.

High variance = overfitting

Performs very well on training data
Performs poorly on test/unseen data

Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [334]:
import seaborn as sns

ds= sns.load_dataset("tips")

#1
ds['tip_percentage']=(ds['tip']/ds['total_bill'])*100

tipPercentageBytime=ds.groupby(['day','time'])['tip_percentage'].mean()

revenue = ds.groupby(["day", "time"])["total_bill"].sum()

print(revenue)

highest = revenue.idxmax()
value = revenue.max()

print("Highest Revenue Segment:", highest)
print("Revenue:", value)

day   time  
Thur  Lunch     1077.55
      Dinner      18.78
Fri   Lunch       89.92
      Dinner     235.96
Sat   Lunch        0.00
      Dinner    1778.40
Sun   Lunch        0.00
      Dinner    1627.16
Name: total_bill, dtype: float64
Highest Revenue Segment: ('Sat', 'Dinner')
Revenue: 1778.4


/var/folders/_d/wnx6skx965v3ctrg5fcbqf_c0000gn/T/ipykernel_30760/2616274131.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tipPercentageBytime=ds.groupby(['day','time'])['tip_percentage'].mean()
/var/folders/_d/wnx6skx965v3ctrg5fcbqf_c0000gn/T/ipykernel_30760/2616274131.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  revenue = ds.groupby(["day", "time"])["total_bill"].sum()
